spring:
  main:
    log-startup-info: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:

server:
  port: 8080
